import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Life in the UAE. Everyday living in Dubai and Abu Dhabi | The Orange Code',
  description: 'A calm, practical overview of life in the UAE for expats and newcomers from around the world. Learn about daily life, culture, housing, transport and weekends in Dubai and Abu Dhabi.',
  keywords: [
    'life in the UAE',
    'living in Dubai',
    'living in Abu Dhabi',
    'UAE lifestyle',
    'expat life UAE',
    'life in UAE for expats',
    'living in Dubai as an expat',
    'living in Abu Dhabi as an expat',
    'UAE lifestyle guide',
    'daily life in UAE',
    'UAE culture and lifestyle',
    'Dubai lifestyle',
    'Abu Dhabi lifestyle',
    'UAE expat life',
    'life in the Emirates',
    'UAE living guide',
    'moving to the UAE',
    'UAE expat guide',
    'Dubai expat guide',
    'Abu Dhabi expat guide',
    'UAE housing',
    'UAE transport',
    'UAE weekends',
    'UAE events',
    'UAE experiences',
    'UAE culture',
    'UAE etiquette',
    'UAE safety',
    'UAE weather',
    'UAE schools',
    'UAE healthcare',
    'UAE neighborhoods',
    'UAE food',
    'UAE restaurants',
    'UAE shopping',
    'UAE travel',
    'UAE holidays',
    'UAE Ramadan',
    'UAE expat community',
    'UAE international schools',
    'UAE cost of living',
    'UAE visa',
    'UAE residency',
    'working in UAE',
    'studying in UAE',
    'UAE business',
    'UAE career',
    'UAE opportunities',
    'UAE diversity',
    'UAE multicultural',
    'UAE international',
    'UAE expat families',
    'UAE expat students',
    'UAE expat professionals',
    'UAE retirement',
    'UAE second career',
    'UAE entrepreneurs',
    'UAE young professionals',
    'UAE families',
    'Dubai neighborhoods',
    'Abu Dhabi neighborhoods',
    'UAE metro',
    'UAE taxis',
    'UAE driving',
    'UAE supermarkets',
    'UAE delivery',
    'UAE halal food',
    'UAE desert',
    'UAE beaches',
    'UAE museums',
    'UAE art',
    'UAE concerts',
    'UAE sports',
    'UAE Formula 1',
    'UAE festivals',
    'UAE heritage',
    'UAE traditions',
    'UAE customs',
    'UAE dress code',
    'UAE communication',
    'UAE public holidays',
    'UAE National Day',
    'UAE Eid',
    'UAE Arabic',
    'UAE English',
    'UAE languages',
    'UAE emirates',
    'Sharjah',
    'Ras Al Khaimah',
    'UAE best emirates',
    'UAE where to live',
    'UAE expat safety',
    'UAE family safety',
    'UAE solo travel',
    'UAE weather seasons',
    'UAE summer',
    'UAE winter',
    'UAE climate',
    'UAE temperature',
    'UAE air conditioning',
    'UAE outdoor activities',
    'UAE indoor activities',
    'UAE relocation',
    'UAE moving guide',
    'UAE newcomer guide',
    'UAE first time',
    'UAE beginners guide',
    'UAE practical guide',
    'UAE everyday life',
    'UAE daily routine',
    'UAE work life',
    'UAE social life',
    'UAE weekend activities',
    'UAE things to do',
    'UAE places to visit',
    'UAE attractions',
    'UAE entertainment',
    'UAE nightlife',
    'UAE cafes',
    'UAE restaurants Dubai',
    'UAE restaurants Abu Dhabi',
    'UAE street food',
    'UAE fine dining',
    'UAE world cuisine',
    'UAE international cuisine',
    'UAE grocery shopping',
    'UAE daily errands',
    'UAE services',
    'UAE infrastructure',
    'UAE modern',
    'UAE development',
    'UAE growth',
    'UAE opportunities',
    'UAE career growth',
    'UAE business opportunities',
    'UAE tax benefits',
    'UAE no tax',
    'UAE tax free',
    'UAE international companies',
    'UAE regional headquarters',
    'UAE emerging industries',
    'UAE shopping malls',
    'UAE parks',
    'UAE beaches Dubai',
    'UAE beaches Abu Dhabi',
    'UAE water activities',
    'UAE desert safari',
    'UAE hiking',
    'UAE nature',
    'UAE mangroves',
    'UAE kayaking',
    'UAE cultural events',
    'UAE art galleries',
    'UAE museums Dubai',
    'UAE museums Abu Dhabi',
    'UAE heritage sites',
    'UAE local festivals',
    'UAE international events',
    'UAE concerts Dubai',
    'UAE concerts Abu Dhabi',
    'UAE sports events',
    'UAE football',
    'UAE tennis',
    'UAE international artists',
    'UAE performances',
    'UAE shows',
    'UAE entertainment venues',
    'UAE dining scene',
    'UAE cafe culture',
    'UAE food scene',
    'UAE culinary',
    'UAE international food',
    'UAE local food',
    'UAE Emirati food',
    'UAE Middle Eastern food',
    'UAE Asian food',
    'UAE European food',
    'UAE American food',
    'UAE food delivery',
    'UAE grocery delivery',
    'UAE online shopping',
    'UAE convenience',
    'UAE modern services',
    'UAE quality of life',
    'UAE standard of living',
    'UAE lifestyle quality',
    'UAE expat lifestyle',
    'UAE international lifestyle',
    'UAE multicultural lifestyle',
    'UAE diverse lifestyle',
    'UAE global lifestyle',
    'UAE cosmopolitan',
    'UAE modern city',
    'UAE urban living',
    'UAE city life',
    'UAE metropolitan',
    'UAE international city',
    'UAE global city',
    'UAE hub',
    'UAE gateway',
    'UAE base',
    'UAE location',
    'UAE strategic location',
    'UAE travel hub',
    'UAE connectivity',
    'UAE flights',
    'UAE airport',
    'UAE Dubai airport',
    'UAE Abu Dhabi airport',
    'UAE regional travel',
    'UAE weekend trips',
    'UAE short trips',
    'UAE Europe travel',
    'UAE Asia travel',
    'UAE Africa travel',
    'UAE Middle East travel',
    'UAE GCC travel',
    'UAE nearby countries',
    'UAE travel opportunities',
    'UAE travel base',
    'UAE expat travel',
    'UAE weekend getaways',
    'UAE holiday destinations',
    'UAE vacation',
    'UAE holidays',
    'UAE time off',
    'UAE work life balance',
    'UAE work culture',
    'UAE office hours',
    'UAE working hours',
    'UAE business hours',
    'UAE school hours',
    'UAE prayer times',
    'UAE traffic',
    'UAE rush hour',
    'UAE evening life',
    'UAE nightlife',
    'UAE social scene',
    'UAE community',
    'UAE expat community',
    'UAE international community',
    'UAE multicultural community',
    'UAE diverse community',
    'UAE social life',
    'UAE networking',
    'UAE friendships',
    'UAE relationships',
    'UAE connections',
    'UAE social connections',
    'UAE professional network',
    'UAE business network',
    'UAE social network',
    'UAE community events',
    'UAE social events',
    'UAE gatherings',
    'UAE meetups',
    'UAE clubs',
    'UAE groups',
    'UAE organizations',
    'UAE associations',
    'UAE societies',
    'UAE expat groups',
    'UAE nationality groups',
    'UAE country groups',
    'UAE professional groups',
    'UAE interest groups',
    'UAE hobby groups',
    'UAE sports clubs',
    'UAE fitness',
    'UAE gym',
    'UAE exercise',
    'UAE outdoor fitness',
    'UAE indoor fitness',
    'UAE wellness',
    'UAE health',
    'UAE healthcare',
    'UAE hospitals',
    'UAE clinics',
    'UAE medical',
    'UAE doctors',
    'UAE healthcare system',
    'UAE medical care',
    'UAE health insurance',
    'UAE medical insurance',
    'UAE insurance',
    'UAE coverage',
    'UAE benefits',
    'UAE employee benefits',
    'UAE work benefits',
    'UAE compensation',
    'UAE salary',
    'UAE income',
    'UAE earnings',
    'UAE tax free income',
    'UAE savings',
    'UAE financial',
    'UAE money',
    'UAE finance',
    'UAE banking',
    'UAE banks',
    'UAE accounts',
    'UAE credit cards',
    'UAE loans',
    'UAE mortgages',
    'UAE property',
    'UAE real estate',
    'UAE housing market',
    'UAE rental market',
    'UAE property market',
    'UAE apartments',
    'UAE villas',
    'UAE studios',
    'UAE one bedroom',
    'UAE two bedroom',
    'UAE three bedroom',
    'UAE four bedroom',
    'UAE penthouses',
    'UAE luxury',
    'UAE premium',
    'UAE high end',
    'UAE affordable',
    'UAE budget',
    'UAE cost',
    'UAE prices',
    'UAE rent',
    'UAE rental',
    'UAE lease',
    'UAE tenancy',
    'UAE accommodation',
    'UAE housing options',
    'UAE living options',
    'UAE residential',
    'UAE residential areas',
    'UAE neighborhoods',
    'UAE districts',
    'UAE communities',
    'UAE gated communities',
    'UAE compounds',
    'UAE residential compounds',
    'UAE family compounds',
    'UAE expat compounds',
    'UAE international compounds',
    'UAE residential towers',
    'UAE high rise',
    'UAE skyscrapers',
    'UAE modern buildings',
    'UAE new developments',
    'UAE master planned',
    'UAE planned communities',
    'UAE integrated communities',
    'UAE mixed use',
    'UAE residential commercial',
    'UAE live work play',
    'UAE amenities',
    'UAE facilities',
    'UAE services',
    'UAE maintenance',
    'UAE security',
    'UAE safety',
    'UAE gated',
    'UAE access control',
    'UAE 24/7 security',
    'UAE CCTV',
    'UAE surveillance',
    'UAE safe',
    'UAE secure',
    'UAE protected',
    'UAE guarded',
    'UAE monitored',
    'UAE patrolled',
    'UAE low crime',
    'UAE crime rate',
    'UAE safety record',
    'UAE security measures',
    'UAE law enforcement',
    'UAE police',
    'UAE emergency services',
    'UAE 999',
    'UAE emergency',
    'UAE help',
    'UAE support',
    'UAE assistance',
    'UAE rules',
    'UAE regulations',
    'UAE laws',
    'UAE legal',
    'UAE compliance',
    'UAE guidelines',
    'UAE standards',
    'UAE requirements',
    'UAE obligations',
    'UAE responsibilities',
    'UAE rights',
    'UAE freedoms',
    'UAE tolerance',
    'UAE respect',
    'UAE mutual respect',
    'UAE cultural respect',
    'UAE religious respect',
    'UAE social respect',
    'UAE professional respect',
    'UAE personal respect',
    'UAE dignity',
    'UAE honor',
    'UAE values',
    'UAE principles',
    'UAE ethics',
    'UAE morals',
    'UAE beliefs',
    'UAE traditions',
    'UAE customs',
    'UAE practices',
    'UAE rituals',
    'UAE ceremonies',
    'UAE celebrations',
    'UAE festivals',
    'UAE holidays',
    'UAE public holidays',
    'UAE national holidays',
    'UAE religious holidays',
    'UAE Islamic holidays',
    'UAE Eid',
    'UAE Eid Al Fitr',
    'UAE Eid Al Adha',
    'UAE Ramadan',
    'UAE fasting',
    'UAE iftar',
    'UAE suhoor',
    'UAE National Day',
    'UAE Union Day',
    'UAE Commemoration Day',
    'UAE New Year',
    'UAE holidays calendar',
    'UAE holiday schedule',
    'UAE holiday dates',
    'UAE holiday periods',
    'UAE holiday seasons',
    'UAE holiday planning',
    'UAE holiday preparation',
    'UAE holiday expectations',
    'UAE holiday behavior',
    'UAE holiday etiquette',
    'UAE holiday customs',
    'UAE holiday traditions',
    'UAE holiday practices',
    'UAE holiday observance',
    'UAE holiday participation',
    'UAE holiday respect',
    'UAE holiday understanding',
    'UAE holiday awareness',
    'UAE holiday knowledge',
    'UAE holiday information',
    'UAE holiday guide',
    'UAE holiday tips',
    'UAE holiday advice',
    'UAE holiday help',
    'UAE holiday support',
    'UAE holiday resources',
    'UAE holiday materials',
    'UAE holiday content',
    'UAE holiday articles',
    'UAE holiday blogs',
    'UAE holiday websites',
    'UAE holiday platforms',
    'UAE holiday services',
    'UAE holiday providers',
    'UAE holiday experts',
    'UAE holiday consultants',
    'UAE holiday advisors',
    'UAE holiday guides',
    'UAE holiday trainers',
    'UAE holiday educators',
    'UAE holiday teachers',
    'UAE holiday instructors',
    'UAE holiday coaches',
    'UAE holiday mentors',
    'UAE holiday facilitators',
    'UAE holiday specialists',
    'UAE holiday professionals',
    'UAE holiday practitioners',
    'UAE holiday consultants UAE',
    'UAE holiday advisors UAE',
    'UAE holiday guides UAE',
    'UAE holiday trainers UAE',
    'UAE holiday educators UAE',
    'UAE holiday teachers UAE',
    'UAE holiday instructors UAE',
    'UAE holiday coaches UAE',
    'UAE holiday mentors UAE',
    'UAE holiday facilitators UAE',
    'UAE holiday specialists UAE',
    'UAE holiday professionals UAE',
    'UAE holiday practitioners UAE',
    'UAE holiday services UAE',
    'UAE holiday providers UAE',
    'UAE holiday experts UAE',
    'UAE holiday consultants Dubai',
    'UAE holiday advisors Dubai',
    'UAE holiday guides Dubai',
    'UAE holiday trainers Dubai',
    'UAE holiday educators Dubai',
    'UAE holiday teachers Dubai',
    'UAE holiday instructors Dubai',
    'UAE holiday coaches Dubai',
    'UAE holiday mentors Dubai',
    'UAE holiday facilitators Dubai',
    'UAE holiday specialists Dubai',
    'UAE holiday professionals Dubai',
    'UAE holiday practitioners Dubai',
    'UAE holiday services Dubai',
    'UAE holiday providers Dubai',
    'UAE holiday experts Dubai',
    'UAE holiday consultants Abu Dhabi',
    'UAE holiday advisors Abu Dhabi',
    'UAE holiday guides Abu Dhabi',
    'UAE holiday trainers Abu Dhabi',
    'UAE holiday educators Abu Dhabi',
    'UAE holiday teachers Abu Dhabi',
    'UAE holiday instructors Abu Dhabi',
    'UAE holiday coaches Abu Dhabi',
    'UAE holiday mentors Abu Dhabi',
    'UAE holiday facilitators Abu Dhabi',
    'UAE holiday specialists Abu Dhabi',
    'UAE holiday professionals Abu Dhabi',
    'UAE holiday practitioners Abu Dhabi',
    'UAE holiday services Abu Dhabi',
    'UAE holiday providers Abu Dhabi',
    'UAE holiday experts Abu Dhabi',
  ],
  alternates: {
    canonical: 'https://www.theorangecode.com/uae-living',
  },
  openGraph: {
    title: 'Life in the UAE. Everyday living in Dubai and Abu Dhabi | The Orange Code',
    description: 'A calm, practical overview of life in the UAE for expats and newcomers from around the world. Learn about daily life, culture, housing, transport and weekends in Dubai and Abu Dhabi.',
    url: 'https://www.theorangecode.com/uae-living',
    siteName: 'The Orange Code',
    images: [
      {
        url: 'https://www.theorangecode.com/og-image',
        width: 1200,
        height: 630,
        alt: 'Life in the UAE - The Orange Code',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Life in the UAE. Everyday living in Dubai and Abu Dhabi',
    description: 'A calm, practical overview of life in the UAE for expats and newcomers from around the world.',
    images: ['https://www.theorangecode.com/og-image'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  other: {
    'ai-topic': 'life in the UAE, living in Dubai, living in Abu Dhabi, UAE lifestyle, expat life UAE, life in UAE for expats, living in Dubai as an expat, living in Abu Dhabi as an expat, UAE lifestyle guide, daily life in UAE, UAE culture and lifestyle, Dubai lifestyle, Abu Dhabi lifestyle, UAE expat life, life in the Emirates, UAE living guide, moving to the UAE, UAE expat guide, Dubai expat guide, Abu Dhabi expat guide',
    'ai-intent': 'researching life in UAE, exploring UAE lifestyle, considering UAE move, UAE expat information, UAE living information, UAE lifestyle information, UAE daily life information, UAE culture information, UAE housing information, UAE transport information, UAE weekend information, UAE events information, UAE experiences information',
    'ai-relevance': 'UAE lifestyle, UAE culture, UAE daily life, UAE expat life, Dubai lifestyle, Abu Dhabi lifestyle, UAE housing, UAE transport, UAE weekends, UAE events, UAE experiences, UAE culture, UAE etiquette, UAE safety, UAE weather, UAE schools, UAE healthcare, UAE neighborhoods, UAE food, UAE restaurants, UAE shopping, UAE travel, UAE holidays, UAE expat community, UAE international schools, UAE cost of living, UAE visa, UAE residency, working in UAE, studying in UAE, UAE business, UAE career, UAE opportunities, UAE diversity, UAE multicultural, UAE international, UAE expat families, UAE expat students, UAE expat professionals, UAE retirement, UAE second career, UAE entrepreneurs, UAE young professionals, UAE families',
    'content-purpose': 'informational guide about life in the UAE for expats and newcomers, lifestyle overview, daily life information, culture information, housing information, transport information, weekend information, events information, experiences information',
    'target-audience': 'expats considering UAE, newcomers to UAE, people researching UAE, people exploring UAE, people interested in UAE, people curious about UAE, people planning UAE move, people thinking about UAE, people considering UAE relocation, people exploring UAE relocation, people researching UAE relocation, people planning UAE relocation, people thinking about UAE relocation, people considering UAE move, people exploring UAE move, people researching UAE move, people planning UAE move, people thinking about UAE move, people considering UAE life, people exploring UAE life, people researching UAE life, people planning UAE life, people thinking about UAE life, people considering UAE lifestyle, people exploring UAE lifestyle, people researching UAE lifestyle, people planning UAE lifestyle, people thinking about UAE lifestyle, people considering UAE living, people exploring UAE living, people researching UAE living, people planning UAE living, people thinking about UAE living, people considering UAE expat life, people exploring UAE expat life, people researching UAE expat life, people planning UAE expat life, people thinking about UAE expat life, people considering Dubai life, people exploring Dubai life, people researching Dubai life, people planning Dubai life, people thinking about Dubai life, people considering Abu Dhabi life, people exploring Abu Dhabi life, people researching Abu Dhabi life, people planning Abu Dhabi life, people thinking about Abu Dhabi life, people considering Dubai lifestyle, people exploring Dubai lifestyle, people researching Dubai lifestyle, people planning Dubai lifestyle, people thinking about Dubai lifestyle, people considering Abu Dhabi lifestyle, people exploring Abu Dhabi lifestyle, people researching Abu Dhabi lifestyle, people planning Abu Dhabi lifestyle, people thinking about Abu Dhabi lifestyle, people considering Dubai living, people exploring Dubai living, people researching Dubai living, people planning Dubai living, people thinking about Dubai living, people considering Abu Dhabi living, people exploring Abu Dhabi living, people researching Abu Dhabi living, people planning Abu Dhabi living, people thinking about Abu Dhabi living, people considering Dubai expat life, people exploring Dubai expat life, people researching Dubai expat life, people planning Dubai expat life, people thinking about Dubai expat life, people considering Abu Dhabi expat life, people exploring Abu Dhabi expat life, people researching Abu Dhabi expat life, people planning Abu Dhabi expat life, people thinking about Abu Dhabi expat life',
    'geographic-focus': 'United Arab Emirates, UAE, Dubai, Abu Dhabi, Sharjah, Ras Al Khaimah, Ajman, Fujairah, Umm Al Quwain, Emirates, Middle East, GCC, Gulf, Arabian Peninsula',
    'content-language': 'en',
    'content-type': 'informational guide, lifestyle overview, daily life guide, culture guide, housing guide, transport guide, weekend guide, events guide, experiences guide, expat guide, newcomer guide, relocation guide, moving guide, living guide, lifestyle information, daily life information, culture information, housing information, transport information, weekend information, events information, experiences information, expat information, newcomer information, relocation information, moving information, living information',
  },
}

export default function UAELivingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
}

