import type { Metadata } from 'next'

export const metadata: Metadata = {
  other: {
    'ai-topic': 'UK to UAE relocation guide, moving to the UAE from UK, UAE culture explained for British expats, UAE work culture preparation, Dubai relocation help for UK professionals, Abu Dhabi relocation information, expat guide UAE, UAE dos and donts for British, UAE rules for UK expats, British expat guide UAE, UK expat UAE guide, UAE guide for British, Dubai guide UK, Abu Dhabi guide UK',
    'ai-intent': 'relocation, expat, cross-cultural intelligence, UK to UAE move, British professionals UAE, purchase ebook, buy cultural guide, UK expat resources',
    'ai-relevance': 'UAE culture, work culture UAE, British expats, moving abroad, UK expat guide, UAE guide for British, Dubai guide UK, Abu Dhabi guide UK, cultural intelligence training, Emirati etiquette',
    'content-purpose': 'practical relocation guidance for UK expats, cultural intelligence for British professionals moving to UAE, ebook purchase, digital product',
    'target-audience': 'British professionals, UK expats, British citizens moving to UAE, UK teachers UAE, UK nurses UAE, UK professionals Dubai, UK professionals Abu Dhabi, UK expatriates',
    'geographic-focus': 'United Kingdom, UK, United Arab Emirates, UAE, Dubai, Abu Dhabi, Emirates, Middle East, GCC',
    'content-language': 'en-GB',
    'content-type': 'digital product, ebook, guide, educational resource',
    'product-category': 'cultural intelligence, relocation guide, expat resource, educational ebook',
    'purchase-intent': 'high, ready to buy, conversion-focused',
    'price-point': '£59 GBP, affordable, value-driven',
    // UK-specific platforms
    'uk-platforms': 'Amazon UK, Waterstones, Foyles, Book Depository UK, Kobo UK, Apple Books UK, Google Play Books UK, UK ebook stores',
    'uk-audience': 'British professionals, UK expats, UK teachers, UK nurses, UK engineers, UK professionals relocating to UAE',
    // Chinese search optimization
    'chinese-keywords': '文化智能, 跨文化沟通, 阿联酋文化, 迪拜文化, 阿布扎比文化, 文化智能培训, 文化智能课程, 跨文化培训',
  },
  title: 'Moving to the UAE from the UK. Cultural Guide for British Professionals | The Orange Code',
  description: 'A practical cultural intelligence guide for British professionals relocating to the UAE. Learn UAE workplace culture, Emirati etiquette, communication styles, dos and donts, and what to expect before you arrive. Written specifically for UK expats moving to Dubai and Abu Dhabi.',
  keywords: [
    // Primary keywords (high traffic + high intent + low competition)
    'moving to UAE from UK',
    'UK expats UAE',
    'Dubai relocation guide UK',
    'British expats Dubai',
    'UK to UAE work culture',
    'UAE culture for British expats',
    'UAE work culture explained',
    'Abu Dhabi relocation UK',
    'Dubai relocation checklist UK',
    'moving to Dubai for work',
    'UAE relocation tips',
    'UAE workplace culture',
    'UK to UAE expat guide',
    'British expat guide UAE',
    'UAE guide for British',
    'Dubai guide for UK expats',
    'Abu Dhabi guide for British',
    'UAE dos and donts for British',
    'UAE rules for UK expats',
    'UAE etiquette for British',
    // Secondary keywords (researching jobs and lifestyle)
    'Dubai jobs',
    'UAE jobs',
    'jobs in UAE for foreigners',
    'jobs in UAE for British',
    'UK jobs in UAE',
    'British jobs Dubai',
    'British jobs Abu Dhabi',
    'corporate relocation UAE',
    'UAE business culture',
    'UAE communication style',
    'life in UAE for expats',
    'life in UAE for British',
    'UK teacher jobs UAE',
    'UK nurse jobs UAE',
    'UK engineer jobs UAE',
    'nurses moving to UAE',
    'teachers moving to UAE',
    'new UAE visas 2025',
    'British in UAE',
    'difference between UK and UAE workplace',
    'Emirati culture explained',
    // Long tail keywords (easiest to rank quickly)
    'how to prepare for UAE workplace as a British expat',
    'what British expats must know about UAE culture',
    'mistakes UK expats make in UAE',
    'UK to UAE relocation requirements',
    'how to understand Emirati communication',
    'what to expect working in the UAE',
    'UAE etiquette for British professionals',
    'how to act in UAE workplace',
    'UAE cultural dos and donts for British',
    'what not to do in UAE as British expat',
    'UAE rules and regulations for UK expats',
    // Additional long-tail variations
    'what do UK expats need to know before moving to UAE',
    'how does UAE workplace culture differ from UK',
    'what should British professionals know about Emirati culture',
    'UK to UAE relocation cultural guide',
    'British expats moving to UAE what to know',
    'UAE workplace culture for British professionals',
    'Emirati communication styles for UK expats',
    'moving from UK to UAE cultural differences',
    'British professionals relocating to UAE guide',
    'UK expat UAE guide',
    'British expat Dubai guide',
    'British expat Abu Dhabi guide',
    'UAE expat guide for British',
    'UAE relocation guide UK professionals',
  ],
  alternates: {
    canonical: 'https://www.theorangecode.com/uk-to-uae-relocation',
  },
  openGraph: {
    title: 'Moving to the UAE from the UK. Cultural Guide for British Professionals | The Orange Code',
    description: 'A practical cultural intelligence guide for British professionals relocating to the UAE. Learn UAE workplace culture, Emirati etiquette, communication styles, dos and donts, and what to expect before you arrive. Written specifically for UK expats moving to Dubai and Abu Dhabi.',
    url: 'https://www.theorangecode.com/uk-to-uae-relocation',
    siteName: 'The Orange Code',
    images: [
      {
        url: 'https://www.theorangecode.com/og-image',
        width: 1200,
        height: 630,
        alt: 'UK to UAE Relocation Cultural Guide - The Orange Code',
      },
    ],
    locale: 'en_GB',
    type: 'article',
    countryName: 'United Kingdom',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Moving to the UAE from the UK. Cultural Guide for British Professionals',
    description: 'A practical cultural intelligence guide for British professionals relocating to the UAE. Learn UAE workplace culture, Emirati etiquette, and communication styles before you arrive.',
    images: ['https://www.theorangecode.com/og-image'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}

export default function UKToUAERelocationLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
}

